CATEGORY_OUTPUT_CODES = {
    "appliances": "AA",
    "brick work": "BB",
    "car": "CC",
    "cooking": "DD",
    "doorbell": "EE",
    "electric": "FF",
    "fence": "GG",
    "fountain": "HH",
    "garden lights": "II",
    "gutters": "JJ",
    "hvac": "KK",
    "irrigation": "LL",
    "mosquito": "MM",
    "painting": "NN",
    "pool": "OO",
    "tree service": "PP",
    "water heater": "QQ",
    "window service": "RR",
}
