CATEGORY_OUTPUT_CODES = {
    "appliances": "ap",
    "brick work": "bw",
    "car": "car",
    "cooking": "cook",
    "doorbell": "db",
    "electric": "el",
    "fence": "fe",
    "fountain": "fo",
    "garden lights": "gl",
    "gutters": "gu",
    "hvac": "hv",
    "irrigation": "ir",
    "mosquito": "ms",
    "painting": "pt",
    "pool": "pl",
    "tree service": "ts",
    "water heater": "wh",
    "window service": "ws",
}
